import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navigation";

export default function Layout({ children }: any) {
	return (
		<>
			<Navigation />
			<Head>
				<title>Will Kee&apos;s Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="shortcut icon" href="/favicon_w.ico" />
			</Head>

			<main className={styles.main}>{children}</main>
		</>
	);
}
